# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: publish

on: 
  push: 
    branches: 
      - draft
  schedule :
    - cron : '*/10 * * * *'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: schdck/create-env-json@v1
      id: create-env
      with:
        file-name: 'personal-blog-278509-1601b8241698.json'
        type: 'service_account'
        project_id: 'personal-blog-278509'
        private_key_id: '1601b8241698a340f19072b6ff34490df80d4ae3',
        private_key: ${{ secrets.GOOGLE_CLOUD_PRIVATE_KEY }}
        client_email: 'minglunwu@personal-blog-278509.iam.gserviceaccount.com',
        client_id: '113191363139112282827',
        auth_uri: 'https://accounts.google.com/o/oauth2/auth',
        token_uri: 'https://oauth2.googleapis.com/token',
        auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs',
        client_x509_cert_url: 'https://www.googleapis.com/robot/v1/metadata/x509/minglunwu%40personal-blog-278509.iam.gserviceaccount.com'
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Checkout Sub Module
      run: |
        git submodule update --init --recursive
        
    - name: Create Output Folder
      run: |
        pelican content -t Hola -o output -s publishconf.py
    
    - name: List Output Folder 
      run: |
        ls output/

    - name: Push to User Repository
      run: |
        git config --local user.name 'github-action[bot]'
        bash ./upload.sh
      
